#!/bin/bash
#11.05.2018
#1-Konfiguration des GPIO-Pins
#1.1-Anlegen der virtuellen Dateien

echo "4" > /sys/class/gpio/export 2> /dev/null
echo "17" > /sys/class/gpio/export 2> /dev/null
echo "22" > /sys/class/gpio/export 2> /dev/null
echo "10" > /sys/class/gpio/export 2> /dev/null
echo "9" > /sys/class/gpio/export 2> /dev/null
echo "11" > /sys/class/gpio/export 2> /dev/null
#1.2-Anpassen der Rechte
sudo chmod a+rwx /sys/class/gpio/gpio4
sudo chmod a+rwx /sys/class/gpio/gpio17
sudo chmod a+rwx /sys/class/gpio/gpio22
sudo chmod a+rwx /sys/class/gpio/gpio10
sudo chmod a+rwx /sys/class/gpio/gpio9
sudo chmod a+rwx /sys/class/gpio/gpio11
#1.3-Deklaration als Ausgänge
echo "out" > /sys/class/gpio/gpio4/direction
echo "out" > /sys/class/gpio/gpio17/direction
echo "out" > /sys/class/gpio/gpio22/direction
echo "out" > /sys/class/gpio/gpio10/direction
echo "out" > /sys/class/gpio/gpio9/direction
echo "out" > /sys/class/gpio/gpio11/direction
#1.4-Alle LEDs ausschalten

echo "0" > /sys/class/gpio/gpio4/value
echo "0" > /sys/class/gpio/gpio17/value
echo "0" > /sys/class/gpio/gpio22/value
echo "0" > /sys/class/gpio/gpio10/value
echo "0" > /sys/class/gpio/gpio9/value
echo "0" > /sys/class/gpio/gpio11/value

#Taster als Eingang konfigurieren
sudo chmod u+rwx /sys/class/gpio/export

echo "7" > /sys/class/gpio/export 2> /dev/null
echo "18" > /sys/class/gpio/export 2> /dev/null

sudo chmod u+rwx /sys/class/gpio/gpio7/direction
sudo chmod u+rwx /sys/class/gpio/gpio18/direction

echo "in" > /sys/class/gpio/gpio7/direction
echo "in" > /sys/class/gpio/gpio18/direction

Punkte1=0
Punkte2=0
mitzaehler=0
zufall1=1
zufall2=7
#-----------------------------START------------------------------#

zufall() {
while true
do
schummeln1=0
schummeln2=0
ergebnis=0

mitzaehler=$(echo $mitzaehler + 1 | bc) #mitzaehler pro Runde +1
if (( $mitzaehler % 30 == 0 )); then #Sobald mitzaehler Teilbare Zahl durch 30 erreicht, Zwischenspielstand Ausgabe

#Alles LEDs anschalten
echo "1" > /sys/class/gpio/gpio4/value
echo "1" > /sys/class/gpio/gpio17/value
echo "1" > /sys/class/gpio/gpio22/value
echo "1" > /sys/class/gpio/gpio10/value
echo "1" > /sys/class/gpio/gpio9/value
echo "1" > /sys/class/gpio/gpio11/value
clear
echo "Zwischenstand: $Punkte1 (Spieler 1) zu $Punkte2 (Spieler 2)"

	for ((i=15; i>0; i--))
	do
	echo "Noch $i Sekunden"
	sleep 1
	done

echo "Es geht weiter!"
sleep 3
clear
Alles LEDs ausschalten
echo "0" > /sys/class/gpio/gpio4/value
echo "0" > /sys/class/gpio/gpio17/value
echo "0" > /sys/class/gpio/gpio22/value
echo "0" > /sys/class/gpio/gpio10/value
echo "0" > /sys/class/gpio/gpio9/value
echo "0" > /sys/class/gpio/gpio11/value
fi


#----------------------------------HÄNGT EVTL MIT DARAN, da nur sehr kurzer, zufälliger Zeitraum, in dem die LEDs ausgehen-------------------------------
#Soll kurzen, unbestimmten Zeitraum wraten, bis nächste LED angeht
warten=0
warten=$((RANDOM % 20 + 5))
warten=$(echo "scale=2; $warten / 10" | bc)
sleep $warten
#---------------------------------------------------------------------------------------------------------------------------------------------------------


schummeln1="$(cat /sys/class/gpio/gpio7/value)"		#Kontrollieren ob Spieler 1 Taster dauerhaft drückt
	if [ "$schummeln1" = "1" ]; then
		while true
		do
		sleep 0.3
		clear
		sleep 0.3
echo " "
echo " "
echo -e "##### 	  #####	  #	#####	#	#####	#####	  	  ##		#####	#####	#   #	#   #	##      ##    ##      ##    #####    #     #######	"
echo -e "#	  #   #	  #	#	#	#	#   #	 	 # #		#	#	#   #	#   #	# ##  ## #    # ##  ## #    #        #        # 	"
echo -e "#	  #   #	  #	#	#	#	#   #		#  #		#	#	#   #	#   #	#   ##   #    #   ##   #    #        #        #		"
echo -e "#####	  #####	  #	#####	#	#####	#####		   #		#####	#	#####	#   #	#        #    #        #    #####    #        #		"
echo -e "    #	  #	  #	#	#	#	##		   #		    #	#	#   #	#   #	#        #    #        #    #        #        #		"
echo -e "    #	  #	  #	#	#	#	# ##		   #		    #	#	#   #	#   #	#        #    #        #    #        #        #		"
echo -e "#####	  #	  #	#####	#####	#####	#  ##		   #		#####	#####	#   #	#####	#        #    #        #    #####    #####    #		"
		done
	fi

schummeln2="$(cat /sys/class/gpio/gpio18/value)"	#Kontrollieren ob Spieler 2 Taster dauerhaft drückt
	if [ "$schummeln2" = "1" ]; then
		while true
			do
			sleep 0.3
			clear
			sleep 0.3
echo " "
echo " "
echo -e "#####    #####   #     #####   #       #####   #####           ###		#####   #####   #   #   #   #   ##      ##    ##      ##    #####    #     #######      "
echo -e "#        #   #   #     #       #       #       #   #          #   #		#       #       #   #   #   #   # ##  ## #    # ##  ## #    #        #        #         "
echo -e "#        #   #   #     #       #       #       #   #         #   ##		#       #       #   #   #   #   #   ##   #    #   ##   #    #        #        #         "
echo -e "#####    #####   #     #####   #       #####   #####            ##		#####   #       #####   #   #   #        #    #        #    #####    #        #         "
echo -e "    #    #       #     #       #       #       ##             ###		    #   #       #   #   #   #   #        #    #        #    #        #        #         "
echo -e "    #    #       #     #       #       #       # ##	      ##		    #   #       #   #   #   #   #   	 #    #        #    #        #        #		"
echo -e "#####    #       #     #####   #####   #####   #  ##         ######	 	#####   #####   #   #   #####   #        #    #        #    #####    #####    #         "
			done
	fi

#---------------------------------------DESHALB--GEHEN--MANCHMAL--DIE--LEDS--AUS-wenn ich auskomemntiere, gehen sie garnicht, nie aus----------------------------

#Wieder alle LEDs ausschalten
echo "0" > /sys/class/gpio/gpio4/value
echo "0" > /sys/class/gpio/gpio17/value
echo "0" > /sys/class/gpio/gpio22/value
echo "0" > /sys/class/gpio/gpio10/value
echo "0" > /sys/class/gpio/gpio9/value
echo "0" > /sys/class/gpio/gpio11/value

#------------------------------------------------------------------------------------------------------------------------------------------------------------------

random=$(( ( RANDOM % "$zufall2" ) + "$zufall1" )) #Zufallsgenerator zwischen 0 und 5 -> random

if [ "$random" = "1" ]; then #LED geht an, wenn random=0
#Verhindert, dass dieselbe LED noch mal dran kommt
zufall1=2
zufall2=6

        echo "1" > /sys/class/gpio/gpio4/value
		time1=$(date +%s%1N) #Vorherige Zeit messen
			while true
			do
			
			ergebnis="$(cat /sys/class/gpio/gpio7/value)" #Taster abfragen/auslesen
			if [ "$ergebnis" = "1" ]; then
			time2=$(date +%s%1N) 			#Spätere Zeit messen
			ergebnis=`expr $time2 - $time1`
				if [ "$ergebnis" -lt "5" ]; then
				echo "Punkt für Spieler 1!"
				Punkte1=$(echo "$Punkte1 + 1" | bc) 		#Punkt für Spieler 1
				break

				else
				echo "Punkt für Spieler 2! Spieler 1 war zu langsam"
				Punkte2=$(echo "$Punkte2 + 1" | bc) 		#Punkt für Spieler 2
				break
				fi
				fi
				done

elif [ "$random" = "2" ]; then	#LED geht an, wenn random=1
zufall1=1
zufall2=7
echo "1" > /sys/class/gpio/gpio17/value

elif [ "$random" = "3" ]; then	#LED geht an, wenn random=2
zufall1=1
zufall2=7
echo "1" > /sys/class/gpio/gpio22/value

else if [ "$random" = "4" ]; then	#LED geht an, wenn random=3
zufall1=1
zufall2=7
echo "1" > /sys/class/gpio/gpio10/value

elif [ "$random" = "5" ]; then	#LED geht an, wenn random=4
zufall1=1
zufall2=7
echo "1" > /sys/class/gpio/gpio9/value

elif [ "$random" = "6" ]; then	#LED geht an, wenn random=5

#Verhindert, dass dieselbe LED noch mal dran kommt
zufall1=1
zufall2=5

echo "1" > /sys/class/gpio/gpio11/value
	time1=$(date +%s%1N) #Vorherige Zeit messen
                        while true
                        do
                        sleep 0.000001
                        ergebnis="$(cat /sys/class/gpio/gpio18/value)" #Taster abfragen/auslesen
                        if [ "$ergebnis" = "1" ]; then
                        time2=$(date +%s%1N)                    #Spätere Zeit messen
                        ergebnis=`expr $time2 - $time1`
                                if [ "$ergebnis" -lt "5" ]; then
                                echo "Punkt für Spieler 2!"
                                Punkte2=$(echo "$Punkte2 + 1" | bc)                #Punkt für Spieler 1
                                break

                                else
				echo "Punkt für Spieler 1! Spieler 2 war zu langsam"
                                Punkte1=$(echo "$Punkte1 + 1" | bc)               #Punkt für Spieler 2
                                break
                                fi
                                fi
                                done
fi
fi
done
}

countdown() {
#Start des Spiels
clear
echo "Countdown beginnt!"
sleep 2

#Ersten 2 LEDs gehen an
echo "1" > /sys/class/gpio/gpio22/value
echo "1" > /sys/class/gpio/gpio10/value
echo "5"
sleep 1

#Ersten 2 LEDs gehen aus
echo "0" > /sys/class/gpio/gpio22/value
echo "0" > /sys/class/gpio/gpio10/value
#Zweite LEDs gehen an
echo "1" > /sys/class/gpio/gpio17/value
echo "1" > /sys/class/gpio/gpio9/value
echo "4"
sleep 1

#Zweite LEDs gehen aus
echo "0" > /sys/class/gpio/gpio17/value
echo "0" > /sys/class/gpio/gpio9/value
#Drítte LEDs gehen an
echo "1" > /sys/class/gpio/gpio4/value
echo "1" > /sys/class/gpio/gpio11/value
echo "3"
sleep 1

#Dritte LEDs gehen aus
echo "0" > /sys/class/gpio/gpio4/value
echo "0" > /sys/class/gpio/gpio11/value
#Vierte LEDs gehen an
echo "1" > /sys/class/gpio/gpio17/value
echo "1" > /sys/class/gpio/gpio9/value
echo "2"
sleep 1

#Vierte LEDs gehen aus
echo "0" > /sys/class/gpio/gpio17/value
echo "0" > /sys/class/gpio/gpio9/value
#Fünfte LEDs gehen an
echo "1" > /sys/class/gpio/gpio22/value
echo "1" > /sys/class/gpio/gpio10/value
echo "1"
sleep 1

#Fünfte LEDs gehen aus
echo "0" > /sys/class/gpio/gpio22/value
echo "0" > /sys/class/gpio/gpio10/value
echo "go!"

zufall
}

countdown
